import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  constructor() {}

  private items = [
    {
      id: 1,
      name: '?',
      color: 'red',
      handles: 'aalleey',
      views: '4,692.69M',
      posts: '2,230',
      followers: '9.97M',
      likes: '417.16M',
      comments: '3.89M',
      shares: '5.74M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp4',
      vdo2: './assets/v/vdo1.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 2,
      name: '?',
      color: 'blue',
      handles: 'aaqib_ashraf28',
      views: '76.20M',
      posts: '439',
      followers: '0.19M',
      likes: '3.56M',
      comments: '0.09M',
      shares: '0.38M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp5',
      vdo2: './assets/v/vdo1.mp5',
      left: '60%',
      top: '7%',
    },
    {
      id: 3,
      name: 'Adeel Chaudhary',
      color: 'red',
      handles: 'adeelchaudry1',
      views: '524.28M',
      posts: '1,910',
      followers: '0.99M',
      likes: '27.73M',
      comments: '0.43M',
      shares: '1.50M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp6',
      vdo2: './assets/v/vdo1.mp6',
      left: '30%',
      top: '20%',
    },
    {
      id: 4,
      name: '?',
      color: 'blue',
      handles: 'aimanzamanofficia82',
      views: '2,866.02M',
      posts: '2,680',
      followers: '7.74M',
      likes: '211.66M',
      comments: '2.08M',
      shares: '3.93M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp7',
      vdo2: './assets/v/vdo1.mp7',
      left: '16%',
      top: '30%',
    },
    {
      id: 5,
      name: '?',
      color: 'red',
      handles: 'aliriaz84',
      views: '1,811.65M',
      posts: '1,296',
      followers: '6.79M',
      likes: '221.39M',
      comments: '2.47M',
      shares: '9.99M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp8',
      vdo2: './assets/v/vdo1.mp8',
      left: '48%',
      top: '35%',
    },
    {
      id: 6,
      name: '?',
      color: 'blue',
      handles: 'ameerhamzajaved1',
      views: '70.44M',
      posts: '278',
      followers: '0.17M',
      likes: '2.96M',
      comments: '0.04M',
      shares: '0.22M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp9',
      vdo2: './assets/v/vdo1.mp9',
      left: '30%',
      top: '43%',
    },
    {
      id: 7,
      name: '?',
      color: 'red',
      handles: 'amnanasir4',
      views: '540.05M',
      posts: '1,780',
      followers: '1.93M',
      likes: '47.31M',
      comments: '0.43M',
      shares: '0.54M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp10',
      vdo2: './assets/v/vdo1.mp10',
      left: '68%',
      top: '50%',
    },
    {
      id: 8,
      name: '?',
      color: 'blue',
      handles: 'angreziwala',
      views: '188.81M',
      posts: '1,660',
      followers: '0.94M',
      likes: '8.39M',
      comments: '0.11M',
      shares: '0.25M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp11',
      vdo2: './assets/v/vdo1.mp11',
      left: '50%',
      top: '56%',
    },
    {
      id: 9,
      name: '?',
      color: 'red',
      handles: 'areeka__haq',
      views: '3,949.97M',
      posts: '733',
      followers: '12.11M',
      likes: '318.23M',
      comments: '4.21M',
      shares: '5.94M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp12',
      vdo2: './assets/v/vdo1.mp12',
      left: '10%',
      top: '58%',
    },
    {
      id: 10,
      name: '?',
      color: 'blue',
      handles: 'aylasworld_',
      views: '77.32M',
      posts: '854',
      followers: '0.25M',
      likes: '4.21M',
      comments: '0.07M',
      shares: '0.05M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp13',
      vdo2: './assets/v/vdo1.mp13',
      left: '16%',
      top: '70%',
    },
    {
      id: 11,
      name: '?',
      color: 'red',
      handles: 'bilalkamokaofficial',
      views: '265.33M',
      posts: '3,248',
      followers: '0.50M',
      likes: '9.40M',
      comments: '0.20M',
      shares: '0.68M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp14',
      vdo2: './assets/v/vdo1.mp14',
      left: '71%',
      top: '73%',
    },
    {
      id: 12,
      name: '?',
      color: 'blue',
      handles: 'ch.zulqarnain25',
      views: '9,183.88M',
      posts: '3,715',
      followers: '17.73M',
      likes: '836.95M',
      comments: '9.19M',
      shares: '18.35M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp15',
      vdo2: './assets/v/vdo1.mp15',
      left: '55%',
      top: '82%',
    },
    {
      id: 13,
      name: '?',
      color: 'red',
      handles: 'chabrarahmad',
      views: '1,591.02M',
      posts: '3,150',
      followers: '3.49M',
      likes: '145.77M',
      comments: '1.21M',
      shares: '1.98M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp16',
      vdo2: './assets/v/vdo1.mp16',
      left: '68%',
      top: '26%',
    },
    {
      id: 14,
      name: '?',
      color: 'blue',
      handles: 'chaudhry_abdulrehman',
      views: '531.66M',
      posts: '841',
      followers: '0.90M',
      likes: '39.37M',
      comments: '0.43M',
      shares: '0.46M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp17',
      vdo2: './assets/v/vdo1.mp17',
      left: '8%',
      top: '88%',
    },
    {
      id: 15,
      name: '?',
      color: 'red',
      handles: 'chdanishofficial',
      views: '188.49M',
      posts: '777',
      followers: '0.29M',
      likes: '8.00M',
      comments: '0.13M',
      shares: '0.44M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp18',
      vdo2: './assets/v/vdo1.mp18',
      left: '40%',
      top: '92%',
    },
    {
      id: 16,
      name: '?',
      color: 'blue',
      handles: 'danial.ahmed8',
      views: '682.80M',
      posts: '1,707',
      followers: '1.38M',
      likes: '45.40M',
      comments: '1.31M',
      shares: '1.57M',
      thmb1: './assets/thmb/thm1.png',
      thmb2: './assets/thmb/thm2.png',
      vdo1: './assets/v/vdo1.mp19',
      vdo2: './assets/v/vdo1.mp19',
      left: '28%',
      top: '2%',
    },
  ];

  getAllItems() {
    return this.items;
  }

  getItem(id: number) {
    return this.items.find((item) => item.id === id);
  }

  getVideoLink(videoId: number): string {
    const videoLink: any = this.items.find((link) => link.id === videoId);
    return videoLink ? videoLink.vdo1 : '';
  }
}
