import { DOCUMENT, JsonPipe } from '@angular/common';
import { Inject, Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  tablet: any;

  // private selectedOptionSource = new BehaviorSubject<string>(
  //   JSON.parse(localStorage.getItem('amTablet') ?? '{}')
  // );
  // selectedOption$ = this.selectedOptionSource.asObservable();

  constructor(@Inject(DOCUMENT) private document: Document) {}

  private data: any = [
    {
      id: 1,
      views: '4,692.69M',
      posts: '2,230',
      followers: '9.97M',
      likes: '417.16M',
      comments: '3.89M',
      shares: '5.74M',
      color: 'red',
      handles: 'aalleey',
      name: 'Ali Fayyaz',
      thmb1: './assets/v/AliFayyaz/1.png',
      thmb2: './assets/v/AliFayyaz/2.png',
      vdo1: './assets/v/AliFayyaz/1.mp4',
      vdo2: './assets/v/AliFayyaz/2.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 2,
      views: '76.20M',
      posts: '439',
      followers: '0.19M',
      likes: '3.56M',
      comments: '0.09M',
      shares: '0.38M',
      color: 'blue',
      handles: 'aaqib_ashraf28',
      name: 'Aaqib Ashraf',
      thmb1: './assets/v/AaqibAshraf/1.png',
      thmb2: './assets/v/AaqibAshraf/2.png',
      vdo1: './assets/v/AaqibAshraf/1.mp4',
      vdo2: './assets/v/AaqibAshraf/2.mp4',
      left: '60%',
      top: '7%',
    },
    {
      id: 3,
      views: '524.28M',
      posts: '1,910',
      followers: '0.99M',
      likes: '27.73M',
      comments: '0.43M',
      shares: '1.50M',
      color: 'red',
      handles: 'adeelchaudry1',
      name: 'Adeel Chaudhary',
      thmb1: './assets/v/AdeelChaudhary/1.png',
      thmb2: './assets/v/AdeelChaudhary/2.png',
      vdo1: './assets/v/AdeelChaudhary/1.mp4',
      vdo2: './assets/v/AdeelChaudhary/2.mp4',
      left: '30%',
      top: '20%',
    },
    {
      id: 4,
      views: '2,866.02M',
      posts: '2,680',
      followers: '7.74M',
      likes: '211.66M',
      comments: '2.08M',
      shares: '3.93M',
      color: 'blue',
      handles: 'aimanzamanofficia82',
      name: 'Aiman zaman',
      thmb1: './assets/v/AimenZaman/1.png',
      thmb2: './assets/v/AimenZaman/2.png',
      vdo1: './assets/v/AimenZaman/1.mp4',
      vdo2: './assets/v/AimenZaman/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 5,
      views: '1,811.65M',
      posts: '1,296',
      followers: '6.79M',
      likes: '221.39M',
      comments: '2.47M',
      shares: '9.99M',
      color: 'red',
      handles: 'aliriaz84',
      name: 'Ali Riaz',
      thmb1: './assets/v/AliRiaz/1.png',
      thmb2: './assets/v/AliRiaz/2.png',
      vdo1: './assets/v/AliRiaz/1.mp4',
      vdo2: './assets/v/AliRiaz/2.mp4',
      left: '48%',
      top: '35%',
    },
    {
      id: 6,
      views: '70.44M',
      posts: '278',
      followers: '0.17M',
      likes: '2.96M',
      comments: '0.04M',
      shares: '0.22M',
      color: 'blue',
      handles: 'ameerhamzajaved1',
      name: 'Meer Hamza',
      thmb1: './assets/v/AmeerHamza/1.png',
      thmb2: './assets/v/AmeerHamza/2.png',
      vdo1: './assets/v/AmeerHamza/1.mp4',
      vdo2: './assets/v/AmeerHamza/2.mp4',
      left: '30%',
      top: '43%',
    },
    {
      id: 7,
      views: '540.05M',
      posts: '1,780',
      followers: '1.93M',
      likes: '47.31M',
      comments: '0.43M',
      shares: '0.54M',
      color: 'red',
      handles: 'amnanasir4',
      name: 'Amna Nasir',
      thmb1: './assets/v/AmnaNasir/1.png',
      thmb2: './assets/v/AmnaNasir/2.png',
      vdo1: './assets/v/AmnaNasir/1.mp4',
      vdo2: './assets/v/AmnaNasir/2.mp4',
      left: '68%',
      top: '50%',
    },
    {
      id: 8,
      views: '188.81M',
      posts: '1,660',
      followers: '0.94M',
      likes: '8.39M',
      comments: '0.11M',
      shares: '0.25M',
      color: 'blue',
      handles: 'angreziwala',
      name: 'Angrezi Wala',
      thmb1: './assets/v/AngreziWala/1.png',
      thmb2: './assets/v/AngreziWala/2.png',
      vdo1: './assets/v/AngreziWala/1.mp4',
      vdo2: './assets/v/AngreziWala/2.mp4',
      left: '50%',
      top: '56%',
    },
    {
      id: 9,
      views: '3,949.97M',
      posts: '733',
      followers: '12.11M',
      likes: '318.23M',
      comments: '4.21M',
      shares: '5.94M',
      color: 'red',
      handles: 'areeka__haq',
      name: 'Areeka',
      thmb1: './assets/v/AreekaHaq/1.png',
      thmb2: './assets/v/AreekaHaq/2.png',
      vdo1: './assets/v/AreekaHaq/1.mp4',
      vdo2: './assets/v/AreekaHaq/2.mp4',
      left: '10%',
      top: '58%',
    },
    {
      id: 10,
      views: '77.32M',
      posts: '854',
      followers: '0.25M',
      likes: '4.21M',
      comments: '0.07M',
      shares: '0.05M',
      color: 'blue',
      handles: 'aylasworld_',
      name: 'Ayla Adnan',
      thmb1: './assets/v/AylasWorld/1.png',
      thmb2: './assets/v/AylasWorld/2.png',
      vdo1: './assets/v/AylasWorld/1.mp4',
      vdo2: './assets/v/AylasWorld/2.mp4',
      left: '16%',
      top: '70%',
    },
    {
      id: 11,
      views: '265.33M',
      posts: '3,248',
      followers: '0.50M',
      likes: '9.40M',
      comments: '0.20M',
      shares: '0.68M',
      color: 'red',
      handles: 'bilalkamokaofficial',
      name: 'Bilal Kamoka Fitness',
      thmb1: './assets/v/BilalKamoka/1.png',
      thmb2: './assets/v/BilalKamoka/2.png',
      vdo1: './assets/v/BilalKamoka/1.mp4',
      vdo2: './assets/v/BilalKamoka/2.mp4',
      left: '71%',
      top: '73%',
    },
    {
      id: 12,
      views: '9,183.88M',
      posts: '3,715',
      followers: '17.73M',
      likes: '836.95M',
      comments: '9.19M',
      shares: '18.35M',
      color: 'blue',
      handles: 'ch.zulqarnain25',
      name: 'Zulqarnain Sikandar',
      thmb1: './assets/v/ChZulqarnain/1.png',
      thmb2: './assets/v/ChZulqarnain/2.png',
      vdo1: './assets/v/ChZulqarnain/1.mp4',
      vdo2: './assets/v/ChZulqarnain/2.mp4',
      left: '55%',
      top: '82%',
    },
    {
      id: 13,
      views: '1,591.02M',
      posts: '3,150',
      followers: '3.49M',
      likes: '145.77M',
      comments: '1.21M',
      shares: '1.98M',
      color: 'red',
      handles: 'chabrarahmad',
      name: 'Ch Abrar AhmAd',
      thmb1: './assets/v/AbrarAhmad/1.png',
      thmb2: './assets/v/AbrarAhmad/2.png',
      vdo1: './assets/v/AbrarAhmad/1.mp4',
      vdo2: './assets/v/AbrarAhmad/2.mp4',
      left: '68%',
      top: '26%',
    },
    {
      id: 14,
      views: '531.66M',
      posts: '841',
      followers: '0.90M',
      likes: '39.37M',
      comments: '0.43M',
      shares: '0.46M',
      color: 'blue',
      handles: 'chaudhry_abdulrehman',
      name: 'Chaudhry Abdul Rehman',
      thmb1: './assets/v/AbdulRehman/1.png',
      thmb2: './assets/v/AbdulRehman/2.png',
      vdo1: './assets/v/AbdulRehman/1.mp4',
      vdo2: './assets/v/AbdulRehman/2.mp4',
      left: '8%',
      top: '88%',
    },
    {
      id: 15,
      views: '188.49M',
      posts: '777',
      followers: '0.29M',
      likes: '8.00M',
      comments: '0.13M',
      shares: '0.44M',
      color: 'red',
      handles: 'chdanishofficial',
      name: 'Ch Danish',
      thmb1: './assets/v/ChDanish/1.png',
      thmb2: './assets/v/ChDanish/2.png',
      vdo1: './assets/v/ChDanish/1.mp4',
      vdo2: './assets/v/ChDanish/2.mp4',
      left: '40%',
      top: '92%',
    },
    {
      id: 16,
      views: '682.80M',
      posts: '1,707',
      followers: '1.38M',
      likes: '45.40M',
      comments: '1.31M',
      shares: '1.57M',
      color: 'blue',
      handles: 'danial.ahmed8',
      name: 'Dr Danial Ahmed',
      thmb1: './assets/v/DanialAhmed/1.png',
      thmb2: './assets/v/DanialAhmed/2.png',
      vdo1: './assets/v/DanialAhmed/1.mp4',
      vdo2: './assets/v/DanialAhmed/2.mp4',
      left: '28%',
      top: '2%',
    },
    {
      id: 17,
      views: '333.53M',
      posts: '719',
      followers: '0.94M',
      likes: '17.99M',
      comments: '0.27M',
      shares: '0.14M',
      color: 'red',
      handles: 'daniyakanwal',
      name: 'Daniya Kanwal',
      thmb1: './assets/v/DaniyaKanwal/1.png',
      thmb2: './assets/v/DaniyaKanwal/2.png',
      vdo1: './assets/v/DaniyaKanwal/1.mp4',
      vdo2: './assets/v/DaniyaKanwal/2.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 18,
      views: '103.38M',
      posts: '959',
      followers: '0.29M',
      likes: '4.83M',
      comments: '0.07M',
      shares: '0.26M',
      color: 'blue',
      handles: 'daniyal.sheikh1',
      name: 'Daniyal Sheikh',
      thmb1: './assets/v/DaniyalSheikh/1.png',
      thmb2: './assets/v/DaniyalSheikh/2.png',
      vdo1: './assets/v/DaniyalSheikh/1.mp4',
      vdo2: './assets/v/DaniyalSheikh/2.mp4',
      left: '60%',
      top: '7%',
    },
    {
      id: 19,
      views: '446.19M',
      posts: '1,473',
      followers: '1.28M',
      likes: '41.23M',
      comments: '0.29M',
      shares: '0.37M',
      color: 'red',
      handles: 'duaafatima_._',
      name: 'C H E E K U',
      thmb1: './assets/v/DuaaFatima/1.png',
      thmb2: './assets/v/DuaaFatima/2.png',
      vdo1: './assets/v/DuaaFatima/1.mp4',
      vdo2: './assets/v/DuaaFatima/2.mp4',
      left: '30%',
      top: '20%',
    },
    {
      id: 20,
      views: '2,154.44M',
      posts: '879',
      followers: '5.19M',
      likes: '152.71M',
      comments: '1.17M',
      shares: '4.08M',
      color: 'blue',
      handles: 'fizamuneeb1',
      name: 'Fiza Fiaz',
      thmb1: './assets/v/FizaMuneeb/1.png',
      thmb2: './assets/v/FizaMuneeb/2.png',
      vdo1: './assets/v/FizaMuneeb/1.mp4',
      vdo2: './assets/v/FizaMuneeb/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 21,
      views: '64.50M',
      posts: '216',
      followers: '0.06M',
      likes: '2.02M',
      comments: '0.04M',
      shares: '0.13M',
      color: 'red',
      handles: 'foodielens_adventures',
      name: 'Foodie Lens Adventures',
      thmb1: './assets/v/FoodieLens/1.png',
      thmb2: './assets/v/FoodieLens/2.png',
      vdo1: './assets/v/FoodieLens/1.mp4',
      vdo2: './assets/v/FoodieLens/2.mp4',
      left: '48%',
      top: '35%',
    },
    {
      id: 22,
      views: '287.45M',
      posts: '1,632',
      followers: '0.43M',
      likes: '8.98M',
      comments: '0.14M',
      shares: '0.88M',
      color: 'blue',
      handles: 'hafizahmedpk',
      name: 'Hafiz Ahmed',
      thmb1: './assets/v/HafizAhmed/1.png',
      thmb2: './assets/v/HafizAhmed/2.png',
      vdo1: './assets/v/HafizAhmed/1.mp4',
      vdo2: './assets/v/HafizAhmed/2.mp4',
      left: '30%',
      top: '43%',
    },
    {
      id: 23,
      views: '891.41M',
      posts: '963',
      followers: '1.67M',
      likes: '35.37M',
      comments: '0.42M',
      shares: '0.92M',
      color: 'red',
      handles: 'hamza_vfx',
      name: 'Hamza Zohaib',
      thmb1: './assets/v/HamzaVFX/1.png',
      thmb2: './assets/v/HamzaVFX/2.png',
      vdo1: './assets/v/HamzaVFX/1.mp4',
      vdo2: './assets/v/HamzaVFX/2.mp4',
      left: '68%',
      top: '50%',
    },
    {
      id: 24,
      views: '58.97M',
      posts: '530',
      followers: '0.11M',
      likes: '2.16M',
      comments: '0.05M',
      shares: '0.04M',
      color: 'blue',
      handles: 'haroonkamal48',
      name: 'Haroon Kamal',
      thmb1: './assets/v/HaroonKamal/1.png',
      thmb2: './assets/v/HaroonKamal/2.png',
      vdo1: './assets/v/HaroonKamal/1.mp4',
      vdo2: './assets/v/HaroonKamal/2.mp4',
      left: '50%',
      top: '56%',
    },
    {
      id: 25,
      views: '3,868.85M',
      posts: '2,372',
      followers: '8.84M',
      likes: '312.81M',
      comments: '2.99M',
      shares: '4.86M',
      color: 'red',
      handles: 'harrisali_01',
      name: 'Harris Ali',
      thmb1: './assets/v/HarrisAli/1.png',
      thmb2: './assets/v/HarrisAli/2.png',
      vdo1: './assets/v/HarrisAli/1.mp4',
      vdo2: './assets/v/HarrisAli/2.mp4',
      left: '10%',
      top: '58%',
    },
    {
      id: 26,
      views: '1,170.12M',
      posts: '3,437',
      followers: '2.51M',
      likes: '113.67M',
      comments: '1.90M',
      shares: '3.10M',
      color: 'blue',
      handles: 'haydarmalik69',
      name: 'Haydar Malik',
      thmb1: './assets/v/HayderMalik/1.png',
      thmb2: './assets/v/HayderMalik/2.png',
      vdo1: './assets/v/HayderMalik/1.mp4',
      vdo2: './assets/v/HayderMalik/2.mp4',
      left: '16%',
      top: '70%',
    },
    {
      id: 27,
      views: '74.85M',
      posts: '1,045',
      followers: '0.07M',
      likes: '1.90M',
      comments: '0.01M',
      shares: '0.16M',
      color: 'red',
      handles: 'hirahomekitchen9611',
      name: 'Hira Home Kitchen',
      thmb1: './assets/v/HiraHome/1.png',
      thmb2: './assets/v/HiraHome/2.png',
      vdo1: './assets/v/HiraHome/1.mp4',
      vdo2: './assets/v/HiraHome/2.mp4',
      left: '71%',
      top: '73%',
    },
    {
      id: 28,
      views: '4,415.55M',
      posts: '3,255',
      followers: '17.71M',
      likes: '473.00M',
      comments: '11.53M',
      shares: '10.00M',
      color: 'blue',
      handles: 'hoormahaveera',
      name: 'Hoor Mahaveera',
      thmb1: './assets/v/HoorMahaveera/1.png',
      thmb2: './assets/v/HoorMahaveera/2.png',
      vdo1: './assets/v/HoorMahaveera/1.mp4',
      vdo2: './assets/v/HoorMahaveera/2.mp4',
      left: '55%',
      top: '82%',
    },
    {
      id: 29,
      views: '83.70M',
      posts: '848',
      followers: '0.15M',
      likes: '3.59M',
      comments: '0.07M',
      shares: '0.44M',
      color: 'red',
      handles: 'i_am_qasim_khan',
      name: 'Qasim Khan',
      thmb1: './assets/v/./assets/v/vdo1.mp32/1.png',
      thmb2: './assets/v/./assets/v/vdo1.mp32/2.png',
      vdo1: './assets/v/./assets/v/vdo1.mp32/1.mp4',
      vdo2: './assets/v/./assets/v/vdo1.mp32/2.mp4',
      left: '68%',
      top: '26%',
    },
    {
      id: 30,
      views: '86.93M',
      posts: '694',
      followers: '0.10M',
      likes: '2.91M',
      comments: '0.05M',
      shares: '0.37M',
      color: 'blue',
      handles: 'iamammad',
      name: 'Ammad Abbasi',
      thmb1: './assets/v/IamAmmad/1.png',
      thmb2: './assets/v/IamAmmad/2.png',
      vdo1: './assets/v/IamAmmad/1.mp4',
      vdo2: './assets/v/IamAmmad/2.mp4',
      left: '8%',
      top: '88%',
    },
    {
      id: 31,
      views: '62.88M',
      posts: '161',
      followers: '0.25M',
      likes: '3.81M',
      comments: '0.03M',
      shares: '0.08M',
      color: 'red',
      handles: 'irfanjunejo',
      name: 'Irfan Junejo',
      thmb1: './assets/v/IrfanJunejo/1.png',
      thmb2: './assets/v/IrfanJunejo/2.png',
      vdo1: './assets/v/IrfanJunejo/1.mp4',
      vdo2: './assets/v/IrfanJunejo/2.mp4',
      left: '40%',
      top: '92%',
    },
    {
      id: 32,
      views: '9,829.58M',
      posts: '3,192',
      followers: '20.93M',
      likes: '810.39M',
      comments: '9.35M',
      shares: '14.53M',
      color: 'blue',
      handles: 'kanwal.135',
      name: 'Kanwalay',
      thmb1: './assets/v/KanwalAftab/1.png',
      thmb2: './assets/v/KanwalAftab/2.png',
      vdo1: './assets/v/KanwalAftab/1.mp4',
      vdo2: './assets/v/KanwalAftab/2.mp4',
      left: '28%',
      top: '2%',
    },
    {
      id: 33,
      views: '23.30M',
      posts: '388',
      followers: '0.07M',
      likes: '0.96M',
      comments: '0.01M',
      shares: '0.03M',
      color: 'red',
      handles: 'kaziakber',
      name: 'Kazi Akber',
      thmb1: './assets/v/KaziAkber/1.png',
      thmb2: './assets/v/KaziAkber/2.png',
      vdo1: './assets/v/KaziAkber/1.mp4',
      vdo2: './assets/v/KaziAkber/2.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 34,
      views: '1,274.83M',
      posts: '1,490',
      followers: '1.44M',
      likes: '53.61M',
      comments: '2.37M',
      shares: '1.46M',
      color: 'blue',
      handles: 'ken_doll_dubai',
      name: 'Ken Doll Dubai',
      thmb1: './assets/v/KenDoll/1.png',
      thmb2: './assets/v/KenDoll/2.png',
      vdo1: './assets/v/KenDoll/1.mp4',
      vdo2: './assets/v/KenDoll/2.mp4',
      left: '60%',
      top: '7%',
    },
    {
      id: 35,
      views: '37.73M',
      posts: '127',
      followers: '0.06M',
      likes: '1.20M',
      comments: '0.02M',
      shares: '0.06M',
      color: 'red',
      handles: 'khadjia_malik',
      name: 'Khadija Malik',
      thmb1: './assets/v/KhadijaMalik/1.png',
      thmb2: './assets/v/KhadijaMalik/2.png',
      vdo1: './assets/v/KhadijaMalik/1.mp4',
      vdo2: './assets/v/KhadijaMalik/2.mp4',
      left: '30%',
      top: '20%',
    },
    {
      id: 36,
      views: '19.26M',
      posts: '291',
      followers: '0.02M',
      likes: '0.72M',
      comments: '0.02M',
      shares: '0.12M',
      color: 'blue',
      handles: 'kiyanieatspk',
      name: 'Usama Kiyani',
      thmb1: './assets/v/UsamaKiyani/1.png',
      thmb2: './assets/v/UsamaKiyani/2.png',
      vdo1: './assets/v/UsamaKiyani/1.mp4',
      vdo2: './assets/v/UsamaKiyani/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 37,
      views: '1,767.05M',
      posts: '1,630',
      followers: '3.96M',
      likes: '153.27M',
      comments: '1.25M',
      shares: '1.51M',
      color: 'red',
      handles: 'laraiblk',
      name: 'Laraib Khalid',
      thmb1: './assets/v/LaraibKhalid/1.png',
      thmb2: './assets/v/LaraibKhalid/2.png',
      vdo1: './assets/v/LaraibKhalid/1.mp4',
      vdo2: './assets/v/LaraibKhalid/2.mp4',
      left: '48%',
      top: '35%',
    },
    {
      id: 38,
      views: '35.66M',
      posts: '56',
      followers: '0.11M',
      likes: '1.65M',
      comments: '0.01M',
      shares: '0.09M',
      color: 'blue',
      handles: 'm1danial',
      name: 'Muhammad Danial',
      thmb1: './assets/v/M1Danial/1.png',
      thmb2: './assets/v/M1Danial/2.png',
      vdo1: './assets/v/M1Danial/1.mp4',
      vdo2: './assets/v/M1Danial/2.mp4',
      left: '30%',
      top: '43%',
    },
    {
      id: 39,
      views: '1,066.16M',
      posts: '1,827',
      followers: '2.77M',
      likes: '103.60M',
      comments: '1.12M',
      shares: '0.97M',
      color: 'red',
      handles: 'maazsafder',
      name: 'Maaz Safder',
      thmb1: './assets/v/MaazSafder/1.png',
      thmb2: './assets/v/MaazSafder/2.png',
      vdo1: './assets/v/MaazSafder/1.mp4',
      vdo2: './assets/v/MaazSafder/2.mp4',
      left: '68%',
      top: '50%',
    },
    {
      id: 40,
      views: '60.75M',
      posts: '534',
      followers: '0.18M',
      likes: '3.69M',
      comments: '0.03M',
      shares: '0.06M',
      color: 'blue',
      handles: 'mominamunir',
      name: 'Momina Munir',
      thmb1: './assets/v/MominaMunir/1.png',
      thmb2: './assets/v/MominaMunir/2.png',
      vdo1: './assets/v/MominaMunir/1.mp4',
      vdo2: './assets/v/MominaMunir/2.mp4',
      left: '50%',
      top: '56%',
    },
    {
      id: 41,
      views: '2,723.74M',
      posts: '1,972',
      followers: '9.81M',
      likes: '234.25M',
      comments: '2.59M',
      shares: '5.30M',
      color: 'red',
      handles: 'mr_battery',
      name: 'Mr Battery',
      thmb1: './assets/v/MrBattery/1.png',
      thmb2: './assets/v/MrBattery/2.png',
      vdo1: './assets/v/MrBattery/1.mp4',
      vdo2: './assets/v/MrBattery/2.mp4',
      left: '10%',
      top: '58%',
    },
    {
      id: 42,
      views: '3,392.29M',
      posts: '3,781',
      followers: '9.67M',
      likes: '238.48M',
      comments: '2.48M',
      shares: '5.12M',
      color: 'blue',
      handles: 'mujtabalakhani123',
      name: 'Mujtaba Lakhani',
      thmb1: './assets/v/MujtabaLakhani/1.png',
      thmb2: './assets/v/MujtabaLakhani/2.png',
      vdo1: './assets/v/MujtabaLakhani/1.mp4',
      vdo2: './assets/v/MujtabaLakhani/2.mp4',
      left: '16%',
      top: '70%',
    },
    {
      id: 43,
      views: '2,022.31M',
      posts: '1,457',
      followers: '5.67M',
      likes: '157.13M',
      comments: '1.45M',
      shares: '5.08M',
      color: 'red',
      handles: 'muneebkhanmoni',
      name: 'Muneeb Khan',
      thmb1: './assets/v/MuneebKhanMoni/1.png',
      thmb2: './assets/v/MuneebKhanMoni/2.png',
      vdo1: './assets/v/MuneebKhanMoni/1.mp4',
      vdo2: './assets/v/MuneebKhanMoni/2.mp4',
      left: '71%',
      top: '73%',
    },
    {
      id: 44,
      views: '35.85M',
      posts: '183',
      followers: '0.05M',
      likes: '0.83M',
      comments: '0.01M',
      shares: '0.03M',
      color: 'blue',
      handles: 'mystapaki',
      name: 'Bilal Hassan',
      thmb1: './assets/v/MystaPaki/1.png',
      thmb2: './assets/v/MystaPaki/2.png',
      vdo1: './assets/v/MystaPaki/1.mp4',
      vdo2: './assets/v/MystaPaki/2.mp4',
      left: '55%',
      top: '82%',
    },
    {
      id: 45,
      views: '11.86M',
      posts: '170',
      followers: '0.05M',
      likes: '0.44M',
      comments: '0.00M',
      shares: '0.00M',
      color: 'red',
      handles: 'omnomzilla',
      name: 'Omnomzilla',
      thmb1: './assets/v/AliSomroo/1.png',
      thmb2: './assets/v/AliSomroo/2.png',
      vdo1: './assets/v/AliSomroo/1.mp4',
      vdo2: './assets/v/AliSomroo/2.mp4',
      left: '68%',
      top: '26%',
    },
    {
      id: 46,
      views: '22.01M',
      posts: '281',
      followers: '0.02M',
      likes: '0.58M',
      comments: '0.02M',
      shares: '0.06M',
      color: 'blue',
      handles: 'peshawarjunkies',
      name: 'Peshawar Junkies',
      thmb1: './assets/v/PeshawarJunkies/1.png',
      thmb2: './assets/v/PeshawarJunkies/2.png',
      vdo1: './assets/v/PeshawarJunkies/1.mp4',
      vdo2: './assets/v/PeshawarJunkies/2.mp4',
      left: '8%',
      top: '88%',
    },
    {
      id: 47,
      views: '4,839.04M',
      posts: '2,134',
      followers: '10.60M',
      likes: '357.92M',
      comments: '4.03M',
      shares: '6.02M',
      color: 'red',
      handles: 'rabeecak',
      name: 'Rabeeca Kashif',
      thmb1: './assets/v/RabeecaKhan/1.png',
      thmb2: './assets/v/RabeecaKhan/2.png',
      vdo1: './assets/v/RabeecaKhan/1.mp4',
      vdo2: './assets/v/RabeecaKhan/2.mp4',
      left: '40%',
      top: '92%',
    },
    {
      id: 48,
      views: '369.35M',
      posts: '1,495',
      followers: '0.83M',
      likes: '19.26M',
      comments: '0.40M',
      shares: '0.36M',
      color: 'blue',
      handles: 'rehamrafiq1',
      name: 'Reham Rafiq',
      thmb1: './assets/v/RehamRafiq/1.png',
      thmb2: './assets/v/RehamRafiq/2.png',
      vdo1: './assets/v/RehamRafiq/1.mp4',
      vdo2: './assets/v/RehamRafiq/2.mp4',
      left: '28%',
      top: '2%',
    },
    {
      id: 49,
      views: '65.91M',
      posts: '386',
      followers: '0.25M',
      likes: '2.73M',
      comments: '0.08M',
      shares: '0.19M',
      color: 'red',
      handles: 'rehmanyaseen898',
      name: 'AbdulRehman Yaseen',
      thmb1: './assets/v/RehmanYaseen/1.png',
      thmb2: './assets/v/RehmanYaseen/2.png',
      vdo1: './assets/v/RehmanYaseen/1.mp4',
      vdo2: './assets/v/RehmanYaseen/2.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 50,
      views: '2,310.59M',
      posts: '1,511',
      followers: '8.71M',
      likes: '183.89M',
      comments: '2.26M',
      shares: '2.31M',
      color: 'blue',
      handles: 'romaisa.khan._',
      name: 'Romaisa Khan',
      thmb1: './assets/v/RomaisaKhan/1.png',
      thmb2: './assets/v/RomaisaKhan/2.png',
      vdo1: './assets/v/RomaisaKhan/1.mp4',
      vdo2: './assets/v/RomaisaKhan/2.mp4',
      left: '60%',
      top: '7%',
    },
    {
      id: 51,
      views: '1,598.00M',
      posts: '1,713',
      followers: '3.09M',
      likes: '80.55M',
      comments: '0.64M',
      shares: '3.00M',
      color: 'red',
      handles: 'salmannomanofficial',
      name: 'Salman Noman',
      thmb1: './assets/v/SalmanNoman/1.png',
      thmb2: './assets/v/SalmanNoman/2.png',
      vdo1: './assets/v/SalmanNoman/1.mp4',
      vdo2: './assets/v/SalmanNoman/2.mp4',
      left: '30%',
      top: '20%',
    },
    {
      id: 52,
      views: '240.46M',
      posts: '294',
      followers: '0.64M',
      likes: '10.88M',
      comments: '0.73M',
      shares: '0.13M',
      color: 'blue',
      handles: 'samins_family_',
      name: 'Samin Chaudhary',
      thmb1: './assets/v/SaminsFamily/1.png',
      thmb2: './assets/v/SaminsFamily/2.png',
      vdo1: './assets/v/SaminsFamily/1.mp4',
      vdo2: './assets/v/SaminsFamily/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 53,
      views: '88.25M',
      posts: '228',
      followers: '0.11M',
      likes: '2.93M',
      comments: '0.04M',
      shares: '0.43M',
      color: 'red',
      handles: 'samixstreets',
      name: 'Sami X Streets',
      thmb1: './assets/v/Samixstreets/1.png',
      thmb2: './assets/v/Samixstreets/2.png',
      vdo1: './assets/v/Samixstreets/1.mp4',
      vdo2: './assets/v/Samixstreets/2.mp4',
      left: '48%',
      top: '35%',
    },
    {
      id: 54,
      views: '633.97M',
      posts: '1,602',
      followers: '1.50M',
      likes: '43.56M',
      comments: '0.62M',
      shares: '0.49M',
      color: 'blue',
      handles: 'samosiiii',
      name: 'Humna',
      thmb1: './assets/v/Samosiiii/1.png',
      thmb2: './assets/v/Samosiiii/2.png',
      vdo1: './assets/v/Samosiiii/1.mp4',
      vdo2: './assets/v/Samosiiii/2.mp4',
      left: '30%',
      top: '43%',
    },
    {
      id: 55,
      views: '230.74M',
      posts: '2,001',
      followers: '0.67M',
      likes: '17.15M',
      comments: '0.13M',
      shares: '0.11M',
      color: 'red',
      handles: 'saralydia__',
      name: 'Saralydia',
      thmb1: './assets/v/SaraLydia/1.png',
      thmb2: './assets/v/SaraLydia/2.png',
      vdo1: './assets/v/SaraLydia/1.mp4',
      vdo2: './assets/v/SaraLydia/2.mp4',
      left: '68%',
      top: '50%',
    },
    {
      id: 56,
      views: '1,538.76M',
      posts: '2,328',
      followers: '3.22M',
      likes: '132.66M',
      comments: '1.37M',
      shares: '2.25M',
      color: 'blue',
      handles: 'shahtajkhanoffical159',
      name: 'Shahtaj Khan',
      thmb1: './assets/v/ShahtajKhan/1.png',
      thmb2: './assets/v/ShahtajKhan/2.png',
      vdo1: './assets/v/ShahtajKhan/1.mp4',
      vdo2: './assets/v/ShahtajKhan/2.mp4',
      left: '50%',
      top: '56%',
    },
    {
      id: 57,
      views: '1,476.71M',
      posts: '1,702',
      followers: '4.49M',
      likes: '114.85M',
      comments: '1.42M',
      shares: '1.38M',
      color: 'red',
      handles: 'shaizraj',
      name: 'Shaiz Raj',
      thmb1: './assets/v/Shaizraj/1.png',
      thmb2: './assets/v/Shaizraj/2.png',
      vdo1: './assets/v/Shaizraj/1.mp4',
      vdo2: './assets/v/Shaizraj/2.mp4',
      left: '10%',
      top: '58%',
    },
    {
      id: 58,
      views: '12,130.77M',
      posts: '13,840',
      followers: '11.97M',
      likes: '1,004.47M',
      comments: '31.61M',
      shares: '17.52M',
      color: 'blue',
      handles: 'sidmr.rapper4',
      name: 'Sid Mr. Rapper',
      thmb1: './assets/v/SidMrRapper/1.png',
      thmb2: './assets/v/SidMrRapper/2.png',
      vdo1: './assets/v/SidMrRapper/1.mp4',
      vdo2: './assets/v/SidMrRapper/2.mp4',
      left: '16%',
      top: '70%',
    },
    {
      id: 59,
      views: '424.53M',
      posts: '425',
      followers: '1.00M',
      likes: '30.04M',
      comments: '0.87M',
      shares: '1.16M',
      color: 'red',
      handles: 'talha_reviews',
      name: 'Talha Reviews',
      thmb1: './assets/v/TalhaReviews/1.png',
      thmb2: 'TalhaReviews1.mp4/2.png',
      vdo1: './assets/v/TalhaReviews/1.mp4',
      vdo2: 'TalhaReviews1.mp4/2.mp4',
      left: '71%',
      top: '73%',
    },
    {
      id: 60,
      views: '18.25M',
      posts: '153',
      followers: '0.03M',
      likes: '0.62M',
      comments: '0.01M',
      shares: '0.04M',
      color: 'blue',
      handles: 'taste_tou_kar',
      name: 'Mani Eats',
      thmb1: './assets/v/TasteTouKar/1.png',
      thmb2: './assets/v/TasteTouKar/2.png',
      vdo1: './assets/v/TasteTouKar/1.mp4',
      vdo2: './assets/v/TasteTouKar/2.mp4',
      left: '55%',
      top: '82%',
    },
    {
      id: 61,
      views: '15.10M',
      posts: '191',
      followers: '0.02M',
      likes: '0.49M',
      comments: '0.01M',
      shares: '0.08M',
      color: 'red',
      handles: 'tastewithb.offical',
      name: 'Taste With Bilal',
      thmb1: './assets/v/TastewithB/1.png',
      thmb2: './assets/v/TastewithB/2.png',
      vdo1: './assets/v/TastewithB/1.mp4',
      vdo2: './assets/v/TastewithB/2.mp4',
      left: '68%',
      top: '26%',
    },
    {
      id: 62,
      views: '190.47M',
      posts: '777',
      followers: '0.48M',
      likes: '8.93M',
      comments: '0.20M',
      shares: '0.29M',
      color: 'blue',
      handles: 'techusama',
      name: 'Tech Usama',
      thmb1: './assets/v/TechUsama/1.png',
      thmb2: './assets/v/TechUsama/2.png',
      vdo1: './assets/v/TechUsama/1.mp4',
      vdo2: './assets/v/TechUsama/2.mp4',
      left: '8%',
      top: '88%',
    },
    {
      id: 63,
      views: '266.35M',
      posts: '547',
      followers: '0.48M',
      likes: '11.24M',
      comments: '0.38M',
      shares: '0.09M',
      color: 'red',
      handles: 'the_voicefactory',
      name: 'Kanz Ul Eman',
      thmb1: './assets/v/TheVoiceFactory/1.png',
      thmb2: './assets/v/TheVoiceFactory/2.png',
      vdo1: './assets/v/TheVoiceFactory/1.mp4',
      vdo2: './assets/v/TheVoiceFactory/2.mp4',
      left: '40%',
      top: '92%',
    },
    {
      id: 64,
      views: '48.19M',
      posts: '123',
      followers: '0.06M',
      likes: '1.57M',
      comments: '0.02M',
      shares: '0.25M',
      color: 'blue',
      handles: 'trexvlogger',
      name: 'T-REX Vlogger',
      thmb1: './assets/v/TrexVlogger/1.png',
      thmb2: './assets/v/TrexVlogger/2.png',
      vdo1: './assets/v/TrexVlogger/1.mp4',
      vdo2: './assets/v/TrexVlogger/2.mp4',
      left: '28%',
      top: '2%',
    },
    {
      id: 65,
      views: '30.81M',
      posts: '188',
      followers: '0.03M',
      likes: '0.83M',
      comments: '0.03M',
      shares: '0.09M',
      color: 'red',
      handles: 'ukashaumarvlogs',
      name: 'Ukasha Umar',
      thmb1: './assets/v/UkashaUmarVlogs/1.png',
      thmb2: './assets/v/UkashaUmarVlogs/2.png',
      vdo1: './assets/v/UkashaUmarVlogs/1.mp4',
      vdo2: './assets/v/UkashaUmarVlogs/2.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 66,
      views: '3,537.85M',
      posts: '2,502',
      followers: '6.64M',
      likes: '347.20M',
      comments: '3.15M',
      shares: '4.26M',
      color: 'blue',
      handles: 'umereee',
      name: 'Umer Butt',
      thmb1: './assets/v/Umereee/1.png',
      thmb2: './assets/v/Umereee/2.png',
      vdo1: './assets/v/Umereee/1.mp4',
      vdo2: './assets/v/Umereee/2.mp4',
      left: '60%',
      top: '7%',
    },
    {
      id: 67,
      views: '1,531.36M',
      posts: '3,038',
      followers: '3.31M',
      likes: '102.22M',
      comments: '0.87M',
      shares: '1.65M',
      color: 'red',
      handles: 'wajidali703',
      name: 'Wajid Ali Rajpoot',
      thmb1: './assets/v/WajidAli/1.png',
      thmb2: './assets/v/WajidAli/2.png',
      vdo1: './assets/v/WajidAli/1.mp4',
      vdo2: './assets/v/WajidAli/2.mp4',
      left: '30%',
      top: '20%',
    },
    {
      id: 68,
      views: '927.15M',
      posts: '885',
      followers: '2.59M',
      likes: '68.06M',
      comments: '0.49M',
      shares: '0.56M',
      color: 'blue',
      handles: 'zarnabfatimaa',
      name: 'Dr Zarnab Fatima',
      thmb1: './assets/v/ZarnabFatima/1.png',
      thmb2: './assets/v/ZarnabFatima/2.png',
      vdo1: './assets/v/ZarnabFatima/1.mp4',
      vdo2: './assets/v/ZarnabFatima/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 69,
      views: '3,356.11M',
      posts: '6,232',
      followers: '10.42M',
      likes: '274.95M',
      comments: '5.03M',
      shares: '3.86M',
      color: 'red',
      handles: 'zunaira.mahi',
      name: 'Zunaira Mahi',
      thmb1: './assets/v/ZunairaMahi/1.png',
      thmb2: './assets/v/ZunairaMahi/2.png',
      vdo1: './assets/v/ZunairaMahi/1.mp4',
      vdo2: './assets/v/ZunairaMahi/2.mp4',
      left: '48%',
      top: '35%',
    },
    {
      id: 70,
      views: '6,475.50M',
      posts: '10,510',
      followers: '5.90M',
      likes: '277.55M',
      comments: '1.12M',
      shares: '2.55M',
      color: 'blue',
      handles: 'arydigitalasia',
      name: 'ARY',
      thmb1: './assets/v/ary/1.png',
      thmb2: './assets/v/ary/2.png',
      vdo1: './assets/v/ary/1.mp4',
      vdo2: './assets/v/ary/2.mp4',
      left: '30%',
      top: '43%',
    },
    {
      id: 71,
      views: '5,006.88M',
      posts: '32,520',
      followers: '5.04M',
      likes: '263.68M',
      comments: '7.98M',
      shares: '10.10M',
      color: 'red',
      handles: 'arynews.official',
      name: 'ARY',
      thmb1: './assets/v/ary/1.png',
      thmb2: './assets/v/ary/2.png',
      vdo1: './assets/v/ary/1.mp4',
      vdo2: './assets/v/ary/2.mp4',
      left: '68%',
      top: '50%',
    },
    {
      id: 72,
      views: '179.77M',
      posts: '1,509',
      followers: '0.27M',
      likes: '6.58M',
      comments: '0.06M',
      shares: '0.07M',
      color: 'blue',
      handles: 'aryzindagi.tv',
      name: 'ARY',
      thmb1: './assets/v/ary/1.png',
      thmb2: './assets/v/ary/2.png',
      vdo1: './assets/v/ary/1.mp4',
      vdo2: './assets/v/ary/2.mp4',
      left: '50%',
      top: '56%',
    },
    {
      id: 73,
      views: '131.84M',
      posts: '606',
      followers: '0.32M',
      likes: '7.24M',
      comments: '0.03M',
      shares: '0.20M',
      color: 'red',
      handles: 'hoshyarianarynews',
      name: 'ARY',
      thmb1: './assets/v/ary/1.png',
      thmb2: './assets/v/ary/2.png',
      vdo1: './assets/v/ary/1.mp4',
      vdo2: './assets/v/ary/2.mp4',
      left: '10%',
      top: '58%',
    },
    {
      id: 74,
      views: '99.27M',
      posts: '751',
      followers: '0.33M',
      likes: '3.59M',
      comments: '0.04M',
      shares: '0.05M',
      color: 'blue',
      handles: 'tamashaarydigital',
      name: 'ARY',
      thmb1: './assets/v/ary/1.png',
      thmb2: './assets/v/ary/2.png',
      vdo1: './assets/v/ary/1.mp4',
      vdo2: './assets/v/ary/2.mp4',
      left: '16%',
      top: '70%',
    },
    {
      id: 75,
      views: '72.15M',
      posts: '252',
      followers: '0.22M',
      likes: '2.92M',
      comments: '0.02M',
      shares: '0.02M',
      color: 'red',
      handles: 'asports.tv',
      name: 'ARY',
      thmb1: './assets/v/ary/1.png',
      thmb2: './assets/v/ary/2.png',
      vdo1: './assets/v/ary/1.mp4',
      vdo2: './assets/v/ary/2.mp4',
      left: '71%',
      top: '73%',
    },
    {
      id: 76,
      views: '23.06M',
      posts: '78',
      followers: '0.52M',
      likes: '1.87M',
      comments: '0.01M',
      shares: '0.02M',
      color: 'blue',
      handles: 'jeetopakistan.official',
      name: 'ARY',
      thmb1: './assets/v/ary/1.png',
      thmb2: './assets/v/ary/2.png',
      vdo1: './assets/v/ary/1.mp4',
      vdo2: './assets/v/ary/2.mp4',
      left: '55%',
      top: '82%',
    },
    {
      id: 77,
      views: '4,241.44M',
      posts: '11,649',
      followers: '4.87M',
      likes: '211.14M',
      comments: '1.35M',
      shares: '3.07M',
      color: 'red',
      handles: 'humtv_pakistan',
      name: 'HUM',
      thmb1: './assets/v/hum/1.png',
      thmb2: './assets/v/hum/2.png',
      vdo1: './assets/v/hum/1.mp4',
      vdo2: './assets/v/hum/2.mp4',
      left: '68%',
      top: '26%',
    },
    {
      id: 78,
      views: '182.48M',
      posts: '4,481',
      followers: '0.33M',
      likes: '4.33M',
      comments: '0.03M',
      shares: '0.77M',
      color: 'blue',
      handles: 'masalatvofficial',
      name: 'HUM',
      thmb1: './assets/v/hum/1.png',
      thmb2: './assets/v/hum/2.png',
      vdo1: './assets/v/hum/1.mp4',
      vdo2: './assets/v/hum/2.mp4',
      left: '8%',
      top: '88%',
    },
    {
      id: 79,
      views: '29.13M',
      posts: '2,355',
      followers: '0.06M',
      likes: '1.05M',
      comments: '0.02M',
      shares: '0.04M',
      color: 'red',
      handles: 'humnewspakistan',
      name: 'HUM',
      thmb1: './assets/v/hum/1.png',
      thmb2: './assets/v/hum/2.png',
      vdo1: './assets/v/hum/1.mp4',
      vdo2: './assets/v/hum/2.mp4',
      left: '40%',
      top: '92%',
    },
    {
      id: 80,
      views: '11.90M',
      posts: '191',
      followers: '0.03M',
      likes: '0.37M',
      comments: '0.00M',
      shares: '0.01M',
      color: 'blue',
      handles: 'hum.films',
      name: 'HUM',
      thmb1: './assets/v/hum/1.png',
      thmb2: './assets/v/hum/2.png',
      vdo1: './assets/v/hum/1.mp4',
      vdo2: './assets/v/hum/2.mp4',
      left: '28%',
      top: '2%',
    },
    {
      id: 81,
      views: '7,882.84M',
      posts: '15,152',
      followers: '7.75M',
      likes: '371.61M',
      comments: '1.62M',
      shares: '3.29M',
      color: 'red',
      handles: 'harpalgeo',
      name: 'GEO',
      thmb1: './assets/v/geo/1.png',
      thmb2: './assets/v/geo/2.png',
      vdo1: './assets/v/geo/1.mp4',
      vdo2: './assets/v/geo/2.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 82,
      views: '4,203.56M',
      posts: '26,682',
      followers: '5.74M',
      likes: '213.36M',
      comments: '4.51M',
      shares: '8.86M',
      color: 'blue',
      handles: 'geonews',
      name: 'GEO',
      thmb1: './assets/v/geo/1.png',
      thmb2: './assets/v/geo/2.png',
      vdo1: './assets/v/geo/1.mp4',
      vdo2: './assets/v/geo/2.mp4',
      left: '60%',
      top: '7%',
    },
    {
      id: 83,
      views: '621.16M',
      posts: '2,280',
      followers: '0.78M',
      likes: '30.33M',
      comments: '0.29M',
      shares: '0.32M',
      color: 'red',
      handles: 'geohasnamanahai',
      name: 'GEO',
      thmb1: './assets/v/geo/1.png',
      thmb2: './assets/v/geo/2.png',
      vdo1: './assets/v/geo/1.mp4',
      vdo2: './assets/v/geo/2.mp4',
      left: '30%',
      top: '20%',
    },
    {
      id: 84,
      views: '3.32M',
      posts: '283',
      followers: '0.02M',
      likes: '0.14M',
      comments: '0.00M',
      shares: '0.00M',
      color: 'blue',
      handles: 'geo.super',
      name: 'GEO',
      thmb1: './assets/v/geo/1.png',
      thmb2: './assets/v/geo/2.png',
      vdo1: './assets/v/geo/1.mp4',
      vdo2: './assets/v/geo/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 85,
      views: '3,752.38M',
      posts: '31,180',
      followers: '3.58M',
      likes: '149.97M',
      comments: '2.91M',
      shares: '10.24M',
      color: 'red',
      handles: 'bolnews',
      name: 'BOL',
      thmb1: './assets/v/bol/1.png',
      thmb2: './assets/v/bol/2.png',
      vdo1: './assets/v/bol/1.mp4',
      vdo2: './assets/v/bol/2.mp4',
      left: '48%',
      top: '35%',
    },
    {
      id: 86,
      views: '500.61M',
      posts: '6,109',
      followers: '0.94M',
      likes: '20.23M',
      comments: '0.20M',
      shares: '0.32M',
      color: 'blue',
      handles: 'bolentertainment',
      name: 'BOL',
      thmb1: './assets/v/bol/1.png',
      thmb2: './assets/v/bol/2.png',
      vdo1: './assets/v/bol/1.mp4',
      vdo2: './assets/v/bol/2.mp4',
      left: '30%',
      top: '43%',
    },
    {
      id: 87,
      views: '2,704.01M',
      posts: '6,614',
      followers: '4.24M',
      likes: '71.54M',
      comments: '0.44M',
      shares: '1.48M',
      color: 'red',
      handles: 'greenentertainmenttv',
      name: 'Green Entertainment',
      thmb1: './assets/v/green/1.png',
      thmb2: './assets/v/green/2.png',
      vdo1: './assets/v/green/1.mp4',
      vdo2: './assets/v/green/2.mp4',
      left: '68%',
      top: '50%',
    },
    {
      id: 88,
      views: '460.58M',
      posts: '1,295',
      followers: '0.59M',
      likes: '15.17M',
      comments: '0.11M',
      shares: '0.23M',
      color: 'blue',
      handles: 'expresstv_official',
      name: 'Express',
      thmb1: './assets/v/express/1.png',
      thmb2: './assets/v/express/2.png',
      vdo1: './assets/v/express/1.mp4',
      vdo2: './assets/v/express/2.mp4',
      left: '50%',
      top: '56%',
    },
    {
      id: 89,
      views: '113.63M',
      posts: '4,586',
      followers: '0.31M',
      likes: '6.09M',
      comments: '0.00M',
      shares: '0.42M',
      color: 'red',
      handles: 'expressnews_pk',
      name: 'Express',
      thmb1: './assets/v/express/1.png',
      thmb2: './assets/v/express/2.png',
      vdo1: './assets/v/express/1.mp4',
      vdo2: './assets/v/express/2.mp4',
      left: '10%',
      top: '58%',
    },
    {
      id: 90,
      views: '379.08M',
      posts: '2,162',
      followers: '0.45M',
      likes: '10.10M',
      comments: '0.07M',
      shares: '0.31M',
      color: 'blue',
      handles: 'aplusentertainment1',
      name: 'APlus',
      thmb1: './assets/v/APlus/1.png',
      thmb2: './assets/v/APlus/2.png',
      vdo1: './assets/v/APlus/1.mp4',
      vdo2: './assets/v/APlus/2.mp4',
      left: '16%',
      top: '70%',
    },
    {
      id: 91,
      views: '374.46M',
      posts: '1,454',
      followers: '0.58M',
      likes: '11.70M',
      comments: '0.09M',
      shares: '0.17M',
      color: 'red',
      handles: 'desitv10',
      name: 'DRM',
      thmb1: './assets/v/drm/1.png',
      thmb2: './assets/v/drm/2.png',
      vdo1: './assets/v/drm/1.mp4',
      vdo2: './assets/v/drm/2.mp4',
      left: '71%',
      top: '73%',
    },
    {
      id: 92,
      views: '235.84M',
      posts: '2,259',
      followers: '0.83M',
      likes: '6.61M',
      comments: '0.06M',
      shares: '0.12M',
      color: 'blue',
      handles: 'drmdramaofficial',
      name: 'DRM',
      thmb1: './assets/v/drm/1.png',
      thmb2: './assets/v/drm/2.png',
      vdo1: './assets/v/drm/1.mp4',
      vdo2: './assets/v/drm/2.mp4',
      left: '55%',
      top: '82%',
    },
    {
      id: 93,
      views: '196.77M',
      posts: '1,745',
      followers: '0.23M',
      likes: '5.86M',
      comments: '0.03M',
      shares: '0.09M',
      color: 'red',
      handles: 'dramasworldofficial',
      name: 'DRM',
      thmb1: './assets/v/drm/1.png',
      thmb2: './assets/v/drm/2.png',
      vdo1: './assets/v/drm/1.mp4',
      vdo2: './assets/v/drm/2.mp4',
      left: '68%',
      top: '26%',
    },
    {
      id: 94,
      views: '70.89M',
      posts: '139',
      followers: '0.10M',
      likes: '0.90M',
      comments: '0.01M',
      shares: '0.02M',
      color: 'blue',
      handles: 'drmdrama',
      name: 'DRM',
      thmb1: './assets/v/drm/1.png',
      thmb2: './assets/v/drm/2.png',
      vdo1: './assets/v/drm/1.mp4',
      vdo2: './assets/v/drm/2.mp4',
      left: '8%',
      top: '88%',
    },
    {
      id: 95,
      views: '56.48M',
      posts: '1,125',
      followers: '0.09M',
      likes: '1.48M',
      comments: '0.01M',
      shares: '0.03M',
      color: 'red',
      handles: 'turk1official',
      name: 'DRM',
      thmb1: './assets/v/drm/1.png',
      thmb2: './assets/v/drm/2.png',
      vdo1: './assets/v/drm/1.mp4',
      vdo2: './assets/v/drm/2.mp4',
      left: '40%',
      top: '92%',
    },
    {
      id: 100,
      views: '1,338.22M',
      posts: '362',
      followers: '1.02M',
      likes: '15.64M',
      comments: '0.12M',
      shares: '0.45M',
      color: 'blue',
      handles: 'cokestudiopakistan',
      name: 'Coke Studio',
      thmb1: './assets/v/cokestudio/1.png',
      thmb2: './assets/v/cokestudio/2.png',
      vdo1: './assets/v/cokestudio/1.mp4',
      vdo2: './assets/v/cokestudio/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 101,
      views: '115.90M',
      posts: '297',
      followers: '0.33M',
      likes: '3.25M',
      comments: '0.02M',
      shares: '0.05M',
      color: 'red',
      handles: 'khoosatfilms',
      name: 'Khoosat Films',
      thmb1: './assets/v/KhoosatFilms/1.png',
      thmb2: './assets/v/KhoosatFilms/2.png',
      vdo1: './assets/v/KhoosatFilms/1.mp4',
      vdo2: './assets/v/KhoosatFilms/2.mp4',
      left: '48%',
      top: '35%',
    },
    {
      id: 102,
      views: '47.87M',
      posts: '675',
      followers: '0.14M',
      likes: '2.95M',
      comments: '0.08M',
      shares: '0.19M',
      color: 'blue',
      handles: 'eonpodcastfull',
      name: 'EON',
      thmb1: './assets/v/eon/1.png',
      thmb2: './assets/v/eon/2.png',
      vdo1: './assets/v/eon/1.mp4',
      vdo2: './assets/v/eon/2.mp4',
      left: '30%',
      top: '43%',
    },
    {
      id: 103,
      views: '511.16M',
      posts: '4,638',
      followers: '1.61M',
      likes: '40.97M',
      comments: '0.27M',
      shares: '0.33M',
      color: 'red',
      handles: 'pcb',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '68%',
      top: '50%',
    },
    {
      id: 104,
      views: '423.18M',
      posts: '1,540',
      followers: '1.82M',
      likes: '27.24M',
      comments: '0.21M',
      shares: '0.48M',
      color: 'blue',
      handles: 'thepsl',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '50%',
      top: '56%',
    },
    {
      id: 105,
      views: '76.65M',
      posts: '371',
      followers: '0.48M',
      likes: '8.38M',
      comments: '0.11M',
      shares: '0.11M',
      color: 'red',
      handles: 'officialpeshawarzalmi',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '10%',
      top: '58%',
    },
    {
      id: 106,
      views: '65.56M',
      posts: '509',
      followers: '0.19M',
      likes: '5.80M',
      comments: '0.03M',
      shares: '0.03M',
      color: 'blue',
      handles: 'qalandarsofficial',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '16%',
      top: '70%',
    },
    {
      id: 107,
      views: '55.48M',
      posts: '148',
      followers: '0.31M',
      likes: '4.46M',
      comments: '0.03M',
      shares: '0.04M',
      color: 'red',
      handles: 'islamabadunitedpsl',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '71%',
      top: '73%',
    },
    {
      id: 108,
      views: '44.89M',
      posts: '186',
      followers: '0.29M',
      likes: '3.90M',
      comments: '0.03M',
      shares: '0.03M',
      color: 'blue',
      handles: 'multansultanstv',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '55%',
      top: '82%',
    },
    {
      id: 109,
      views: '35.29M',
      posts: '123',
      followers: '0.14M',
      likes: '1.42M',
      comments: '0.01M',
      shares: '0.01M',
      color: 'red',
      handles: 'karachikingsofficial',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '68%',
      top: '26%',
    },
    {
      id: 110,
      views: '32.96M',
      posts: '125',
      followers: '0.12M',
      likes: '1.16M',
      comments: '0.01M',
      shares: '0.01M',
      color: 'blue',
      handles: 'championscuppcb',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '8%',
      top: '88%',
    },
    {
      id: 111,
      views: '17.11M',
      posts: '115',
      followers: '0.14M',
      likes: '1.51M',
      comments: '0.01M',
      shares: '0.01M',
      color: 'red',
      handles: 'gladiatorspurpleforce',
      name: 'PCB',
      thmb1: './assets/v/pcb/1.png',
      thmb2: './assets/v/pcb/2.png',
      vdo1: './assets/v/pcb/1.mp4',
      vdo2: './assets/v/pcb/2.mp4',
      left: '40%',
      top: '92%',
    },
    {
      id: 112,
      views: '239.19M',
      posts: '2,453',
      followers: '0.34M',
      likes: '7.79M',
      comments: '0.12M',
      shares: '0.72M',
      color: 'blue',
      handles: '24entertainmentofficial',
      name: 'City42',
      thmb1: './assets/v/city42/1.png',
      thmb2: './assets/v/city42/2.png',
      vdo1: './assets/v/city42/1.mp4',
      vdo2: './assets/v/city42/2.mp4',
      left: '28%',
      top: '2%',
    },
    {
      id: 113,
      views: '195.73M',
      posts: '3,027',
      followers: '0.33M',
      likes: '6.44M',
      comments: '0.13M',
      shares: '0.26M',
      color: 'red',
      handles: '24newshdofficial',
      name: 'City42',
      thmb1: './assets/v/city42/1.png',
      thmb2: './assets/v/city42/2.png',
      vdo1: './assets/v/city42/1.mp4',
      vdo2: './assets/v/city42/2.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 114,
      views: '139.81M',
      posts: '2,113',
      followers: '0.08M',
      likes: '3.09M',
      comments: '0.07M',
      shares: '0.05M',
      color: 'blue',
      handles: 'kyadramahaiofficial',
      name: 'City42',
      thmb1: './assets/v/city42/1.png',
      thmb2: './assets/v/city42/2.png',
      vdo1: './assets/v/city42/1.mp4',
      vdo2: './assets/v/city42/2.mp4',
      left: '60%',
      top: '7%',
    },
    {
      id: 115,
      views: '95.93M',
      posts: '3,059',
      followers: '0.18M',
      likes: '2.79M',
      comments: '0.10M',
      shares: '0.23M',
      color: 'red',
      handles: 'city42newsofficial',
      name: 'City42',
      thmb1: './assets/v/city42/1.png',
      thmb2: './assets/v/city42/2.png',
      vdo1: './assets/v/city42/1.mp4',
      vdo2: './assets/v/city42/2.mp4',
      left: '30%',
      top: '20%',
    },
    {
      id: 116,
      views: '62.07M',
      posts: '208',
      followers: '0.08M',
      likes: '1.03M',
      comments: '0.01M',
      shares: '0.02M',
      color: 'blue',
      handles: 'teeli.pk',
      name: 'DAWN',
      thmb1: './assets/v/dawn/1.png',
      thmb2: './assets/v/dawn/2.png',
      vdo1: './assets/v/dawn/1.mp4',
      vdo2: './assets/v/dawn/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 117,
      views: '22.05M',
      posts: '4,889',
      followers: '0.08M',
      likes: '0.75M',
      comments: '0.02M',
      shares: '0.06M',
      color: 'red',
      handles: 'dawnnewspakistan',
      name: 'DAWN',
      thmb1: './assets/v/dawn/1.png',
      thmb2: './assets/v/dawn/2.png',
      vdo1: './assets/v/dawn/1.mp4',
      vdo2: './assets/v/dawn/2.mp4',
      left: '48%',
      top: '35%',
    },
    {
      id: 118,
      views: '10.89M',
      posts: '641',
      followers: '0.03M',
      likes: '0.36M',
      comments: '0.01M',
      shares: '0.02M',
      color: 'blue',
      handles: 'dawn_images',
      name: 'DAWN',
      thmb1: './assets/v/dawn/1.png',
      thmb2: './assets/v/dawn/2.png',
      vdo1: './assets/v/dawn/1.mp4',
      vdo2: './assets/v/dawn/2.mp4',
      left: '30%',
      top: '43%',
    },
    {
      id: 119,
      views: '158.69M',
      posts: '1,428',
      followers: '0.73M',
      likes: '3.78M',
      comments: '0.05M',
      shares: '0.30M',
      color: 'red',
      handles: 'oladoc.com',
      name: 'Ola doc',
      thmb1: './assets/v/OlaDoc/1.png',
      thmb2: './assets/v/OlaDoc/2.png',
      vdo1: './assets/v/OlaDoc/1.mp4',
      vdo2: './assets/v/OlaDoc/2.mp4',
      left: '68%',
      top: '50%',
    },
    {
      id: 120,
      views: '187.98M',
      posts: '1,046',
      followers: '0.51M',
      likes: '4.42M',
      comments: '0.06M',
      shares: '0.40M',
      color: 'blue',
      handles: 'marhampk',
      name: 'Marham',
      thmb1: './assets/v/marham/1.png',
      thmb2: './assets/v/marham/2.png',
      vdo1: './assets/v/marham/1.mp4',
      vdo2: './assets/v/marham/2.mp4',
      left: '50%',
      top: '56%',
    },
    {
      id: 121,
      views: '764.40M',
      posts: '12,738',
      followers: '1.11M',
      likes: '33.70M',
      comments: '1.06M',
      shares: '1.92M',
      color: 'red',
      handles: 'suno_newshd',
      name: 'Suno',
      thmb1: './assets/v/suno/1.png',
      thmb2: './assets/v/suno/2.png',
      vdo1: './assets/v/suno/1.mp4',
      vdo2: './assets/v/suno/2.mp4',
      left: '10%',
      top: '58%',
    },
    {
      id: 122,
      views: '139.59M',
      posts: '1,766',
      followers: '0.14M',
      likes: '4.42M',
      comments: '0.04M',
      shares: '0.08M',
      color: 'blue',
      handles: 'showtimewithramizraja',
      name: 'Suno',
      thmb1: './assets/v/suno/1.png',
      thmb2: './assets/v/suno/2.png',
      vdo1: './assets/v/suno/1.mp4',
      vdo2: './assets/v/suno/2.mp4',
      left: '16%',
      top: '70%',
    },
    {
      id: 123,
      views: '692.08M',
      posts: '4,210',
      followers: '0.43M',
      likes: '21.24M',
      comments: '0.31M',
      shares: '0.75M',
      color: 'red',
      handles: 'galaxylollywood',
      name: 'Galaxy Lollywood',
      thmb1: './assets/v/GalaxyLollywood/1.png',
      thmb2: './assets/v/GalaxyLollywood/2.png',
      vdo1: './assets/v/GalaxyLollywood/1.mp4',
      vdo2: './assets/v/GalaxyLollywood/2.mp4',
      left: '71%',
      top: '73%',
    },
    {
      id: 124,
      views: '219.70M',
      posts: '4,381',
      followers: '0.29M',
      likes: '7.07M',
      comments: '0.05M',
      shares: '0.12M',
      color: 'blue',
      handles: 'muntvofficial',
      name: 'MUN',
      thmb1: './assets/v/mun/1.png',
      thmb2: './assets/v/mun/2.png',
      vdo1: './assets/v/mun/1.mp4',
      vdo2: './assets/v/mun/2.mp4',
      left: '55%',
      top: '82%',
    },
    {
      id: 125,
      views: '0.65M',
      posts: '120',
      followers: '0.00M',
      likes: '0.02M',
      comments: '0.00M',
      shares: '0.00M',
      color: 'red',
      handles: 'mun.tv.digital',
      name: 'MUN',
      thmb1: './assets/v/mun/1.png',
      thmb2: './assets/v/mun/2.png',
      vdo1: './assets/v/mun/1.mp4',
      vdo2: './assets/v/mun/2.mp4',
      left: '68%',
      top: '26%',
    },
    {
      id: 126,
      views: '83.01M',
      posts: '3,559',
      followers: '0.24M',
      likes: '3.13M',
      comments: '0.07M',
      shares: '0.31M',
      color: 'blue',
      handles: 'discoverpakistantv',
      name: 'Discover Pakistan',
      thmb1: './assets/v/DiscoverPakistan/1.png',
      thmb2: './assets/v/DiscoverPakistan/2.png',
      vdo1: './assets/v/DiscoverPakistan/1.mp4',
      vdo2: './assets/v/DiscoverPakistan/2.mp4',
      left: '8%',
      top: '88%',
    },
    {
      id: 127,
      views: '56.88M',
      posts: '1,260',
      followers: '0.13M',
      likes: '2.43M',
      comments: '0.02M',
      shares: '0.16M',
      color: 'red',
      handles: 'daisbookgnn',
      name: 'GNN',
      thmb1: './assets/v/gnn/1.png',
      thmb2: './assets/v/gnn/2.png',
      vdo1: './assets/v/gnn/1.mp4',
      vdo2: './assets/v/gnn/2.mp4',
      left: '40%',
      top: '92%',
    },
    {
      id: 128,
      views: '27.39M',
      posts: '18',
      followers: '0.03M',
      likes: '0.39M',
      comments: '0.00M',
      shares: '0.00M',
      color: 'blue',
      handles: 'sharktank_pakistan',
      name: 'Shark Tank',
      thmb1: './assets/v/SharkTank/1.png',
      thmb2: './assets/v/SharkTank/2.png',
      vdo1: './assets/v/SharkTank/1.mp4',
      vdo2: './assets/v/SharkTank/2.mp4',
      left: '28%',
      top: '2%',
    },
    {
      id: 129,
      views: '9.37M',
      posts: '456',
      followers: '0.02M',
      likes: '0.44M',
      comments: '0.00M',
      shares: '0.01M',
      color: 'red',
      handles: 'khelshel',
      name: 'Khel Sheel',
      thmb1: './assets/v/KhelShel/1.png',
      thmb2: './assets/v/KhelShel/2.png',
      vdo1: './assets/v/KhelShel/1.mp4',
      vdo2: './assets/v/KhelShel/2.mp4',
      left: '16%',
      top: '12%',
    },
    {
      id: 130,
      views: '764.93M',
      posts: '8,160',
      followers: '1.05M',
      likes: '29.02M',
      comments: '0.88M',
      shares: '1.38M',
      color: 'blue',
      handles: 'samaadigital',
      name: 'Samaa',
      thmb1: './assets/v/samaa/1.png',
      thmb2: './assets/v/samaa/2.png',
      vdo1: './assets/v/samaa/1.mp4',
      vdo2: './assets/v/samaa/2.mp4',
      left: '60%',
      top: '7%',
    },
    {
      id: 131,
      views: '291.95M',
      posts: '1,416',
      followers: '0.32M',
      likes: '11.37M',
      comments: '0.10M',
      shares: '0.23M',
      color: 'red',
      handles: 'gupshabofficial',
      name: 'Samaa',
      thmb1: './assets/v/samaa/1.png',
      thmb2: './assets/v/samaa/2.png',
      vdo1: './assets/v/samaa/1.mp4',
      vdo2: './assets/v/samaa/2.mp4',
      left: '30%',
      top: '20%',
    },
    {
      id: 132,
      views: '283.00M',
      posts: '1,255',
      followers: '0.64M',
      likes: '10.62M',
      comments: '0.06M',
      shares: '0.18M',
      color: 'blue',
      handles: 'samaaentertainment',
      name: 'Samaa',
      thmb1: './assets/v/samaa/1.png',
      thmb2: './assets/v/samaa/2.png',
      vdo1: './assets/v/samaa/1.mp4',
      vdo2: './assets/v/samaa/2.mp4',
      left: '16%',
      top: '30%',
    },
    {
      id: 133,
      views: '0.41M',
      posts: '208',
      followers: '0.00M',
      likes: '0.01M',
      comments: '0.00M',
      shares: '0.00M',
      color: 'red',
      handles: 'samaapodcast',
      name: 'Samaa',
      thmb1: './assets/v/samaa/1.png',
      thmb2: './assets/v/samaa/2.png',
      vdo1: './assets/v/samaa/1.mp4',
      vdo2: './assets/v/samaa/2.mp4',
      left: '48%',
      top: '35%',
    },
  ];

  getAllItems() {
    if (this.tablet === 'tab1') {
      return this.data.slice(0, 14);
    } else if (this.tablet === 'tab2') {
      return this.data.slice(15, 30);
    } else if (this.tablet === 'tab3') {
      return this.data.slice(31, 45);
    } else if (this.tablet === 'tab4') {
      return this.data.slice(46, 60);
    } else if (this.tablet === 'tab5') {
      return this.data.slice(61, 75);
    } else if (this.tablet === 'tab6') {
      return this.data.slice(76, 91);
    }
  }

  getItem(id: number) {
    // const item = this.data.find((item: any) => item.id === id);
    // console.log(item, 'from srv');

    return this.data.find((item: any) => item.id === id);
  }

  getVideoLink(videoId: number): string {
    const videoLink: any = this.data.find((link: any) => link.id === videoId);
    return videoLink ? videoLink.vdo1 : '';
  }

  setSelectTablet(option: string) {
    this.tablet = option;
    // this.selectedOptionSource.next(option);
  }
}
